### ISSUE TITLE
ggplot 3.4.0 update creates warning in bal.plot()

### ISSUE THREAD

**Issue by markdanese** [ngreifer/cobalt#68] opened 2023-01-31 00:28 UTC
I just installed ggplot 3.4.0 and got the following warning from bal.plot() for a propensity score weighted model created in Matchthem (i.e., using multiple imputations):
```
Warning messages:
1: The following aesthetics were dropped during statistical transformation: weight
ℹ This can happen when ggplot fails to infer the correct grouping structure in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a factor? 
```
This was the code I was running:
```
        bal.plot(
            datasets,
            which.imp = .none,
            var.name = distance_measure,
            which = "both",
            type = "density",
            sample.names = bal_plot_labels,
            colors = c("blue", "yellow")
        ) 
```
I found a similar Github issue in ggplot2 suggesting that there is a change in ggplot2 version 3.4.0 that is causing the error.
https://github.com/tidyverse/ggplot2/issues/5053.

See this specific comment which mentions the need to specify that weight is an aesthetic that can be dropped:  https://github.com/tidyverse/ggplot2/issues/5053#issuecomment-1320924457 

I reverted to ggplot 3.3.6 and the warning was gone, so it seems that this is the issue.

**Comment by ngreifer** [comment] 2023-01-31 06:34
Thank you! I've been neglecting `cobalt` so I didn't see this. I'll fix this shortly.

**Comment by ngreifer** [comment] 2023-01-31 06:42
It seems like this is a bug in `ggplot2` that I have no control over. I think all we can do is wait till it is fixed on their end. Everything in `bal.plot()` works as intended; the warning is spurious. Thanks for bringing it to my attention, though.

**Closed** 2023-11-20 19:07 UTC
